### PR TITLE
Lots of changes...

### PR DESCRIPTION
**Pull request by zharovdv**
I know it's very big for just one commit, but i hope you could take it. I'd spend a lot of time moving silk by hands before i found you script. But it make's not in my way and don't really help. So i make some changes. All new features nearly totaly back compatible with you versions by options.

1) Save/Load options in .ini file
2) Add Ctrl+Break Hint
3) Turn off Online DRC before processing (and restore it after) (For perfomance)
4) On/Off position option
5) Position delta option
6) Fixed size/width option
7) Rotation strategies option
8) Altered rotation option

### CODE REVIEW

**Comment by zharovdv** [comment]
It's formatted with Delphi code formatter (default settings).

**Comment by coffeenmusic** [comment]
I really like your additions, especially the *.ini file. How difficult would it be to add the check boxes to the ini file? Also, when failed placement of designators places them over components, they no longer align with the component, which it would be nice to keep.

**Comment by zharovdv** [comment]
1) Checkboxes.. ops... :)
2) I'll change failed designator rotation in next commit. Just a moment.

**Comment by coffeenmusic** [comment]
Awesome. Thanks!

**Pull request merged**
